### ISSUE TITLE
Empirical Application of Chapter 3

### ISSUE THREAD

**Issue by KatoPachi** [KatoPachi/2020EconometricsTA#1]
## Todo list
- Contents
    - [x] Binary model (Linear probability model, probit model, and logit model)
    - [x] Ordered logit and probit model
    - [x] Multinomial logit model
    - [x] Truncated regression
    - [x] Tobit model (Censored regression model)
    - [x] Poisson regression (Count data model)

## Corrections (10/27)
- [x] drop t-value and p-value
- [x] drop section 1.3 but keep formula of partial effect
- [x] split sample between estimation and prediction purpose
